AnimationPointers:
	table_width 2
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw PikipekAnimation
	dw TrumbeakAnimation
	dw ToucannonAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw CrobatAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw RoseliaAnimation
	dw RoseradeAnimation
	dw ShelmetAnimation
	dw EscavalierAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw TimburrAnimation
	dw GurdurrAnimation
	dw ConkeldurrAnimation
	dw SableyeAnimation
	dw FrillishAnimation
	dw JellicentAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw MudbrayAnimation
	dw MudsdaleAnimation
	dw FomantisAnimation
	dw LurantisAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw FlabebeAnimation
	dw FloetteAnimation
	dw FlorgesAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw SlowkingAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw NuzleafAnimation
	dw ShiftryAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw TyruntAnimation
	dw TyrantrumAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw SteelixAnimation
	dw StarlyAnimation
	dw StaraviaAnimation
	dw StaraptorAnimation
	dw MawileAnimation
	dw DarumakaAnimation
	dw DarmanitanAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw LillipupAnimation
	dw HerdierAnimation
	dw StoutlandAnimation
	dw FroslassAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw TangelaAnimation
	dw TangrowthAnimation
	dw StunfiskAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw KingdraAnimation
	dw PawniardAnimation
	dw BisharpAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw ElectivireAnimation
	dw MagmarAnimation
	dw MagmortarAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw LeafeonAnimation
	dw SylveonAnimation
	dw GlaceonAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw ZangooseAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw HawluchaAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw SwirlixAnimation
	dw SlurpuffAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PinsirAnimation
	dw TynamoAnimation
	dw EelektrikAnimation
	dw EelektrossAnimation
	dw AbsolAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw MurkrowAnimation
	dw HonchkrowAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw UnownAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw StuffulAnimation
	dw BewearAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw ShuckleAnimation
	dw BergmiteAnimation
	dw AvaluggAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw NoibatAnimation
	dw NoivernAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw SandileAnimation
	dw KrokorokAnimation
	dw KrookodileAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonzAnimation
	dw SmeargleAnimation
	dw CryogonalAnimation
	dw GoomyAnimation
	dw SliggooAnimation
	dw GoodraAnimation
	dw MiltankAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw JirachiAnimation
	dw DianceAnimation
	assert_table_length NUM_POKEMON
