BitmasksPointers:
	table_width 2
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw PikipekBitmasks
	dw TrumbeakBitmasks
	dw ToucannonBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	dw RoseliaBitmasks
	dw RoseradeBitmasks
	dw ShelmetBitmasks
	dw EscavalierBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw SableyeBitmasks
	dw FrillishBitmasks
	dw JellicentBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw MudbrayBitmasks
	dw MudsdaleBitmasks
	dw FomantisBitmasks
	dw LurantisBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw SkorupiBitmasks
	dw DrapionBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw FlabebeBitmasks
	dw FloetteBitmasks
	dw FlorgesBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw NuzleafBitmasks
	dw ShiftryBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw TyruntBitmasks
	dw TyrantrumBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw StarlyBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
	dw MawileBitmasks
	dw DarumakaBitmasks
	dw DarmanitanBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw SkrelpBitmasks
	dw DragalgeBitmasks
	dw LillipupBitmasks
	dw HerdierBitmasks
	dw StoutlandBitmasks
	dw FroslassBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw StunfiskBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw ElectivireBitmasks
	dw MagmarBitmasks
	dw MagmortarBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw SylveonBitmasks
	dw GlaceonBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw ZangooseBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw HawluchaBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw SwirlixBitmasks
	dw SlurpuffBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PinsirBitmasks
	dw TynamoBitmasks
	dw EelektrikBitmasks
	dw EelektrossBitmasks
	dw AbsolBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw UnownBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw StuffulBitmasks
	dw BewearBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw ShuckleBitmasks
	dw BergmiteBitmasks
	dw AvaluggBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw NoibatBitmasks
	dw NoivernBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw SandileBitmasks
	dw KrokorokBitmasks
	dw KrookodileBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonzBitmasks
	dw SmeargleBitmasks
	dw CryogonalBitmasks
	dw GoomyBitmasks
	dw SliggooBitmasks
	dw GoodraBitmasks
	dw MiltankBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw JirachiBitmasks
	dw DianceBitmasks
	assert_table_length NUM_POKEMON
