FramesPointers:
	table_width 2
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw PikipekFrames
	dw TrumbeakFrames
	dw ToucannonFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw PikachuFrames
	dw RaichuFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw CutieflyFrames
	dw RibombeeFrames
	dw RoseliaFrames
	dw RoseradeFrames
	dw ShelmetFrames
	dw EscavalierFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw TimburrFrames
	dw GurdurrFrames
	dw ConkeldurrFrames
	dw SableyeFrames
	dw FrillishFrames
	dw JellicentFrames
	dw VenonatFrames
	dw VenomothFrames
	dw MudbrayFrames
	dw MudsdaleFrames
	dw FomantisFrames
	dw LurantisFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw SkorupiFrames
	dw DrapionFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw FlabebeFrames
	dw FloetteFrames
	dw FlorgesFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SwabluFrames
	dw AltariaFrames
	dw GrimerFrames
	dw MukFrames
	dw NuzleafFrames
	dw ShiftryFrames
	dw DrifloonFrames
	dw DrifblimFrames
	dw TyruntFrames
	dw TyrantrumFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw SteelixFrames
	dw StarlyFrames
	dw StaraviaFrames
	dw StaraptorFrames
	dw MawileFrames
	dw DarumakaFrames
	dw DarmanitanFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw LillipupFrames
	dw HerdierFrames
	dw StoutlandFrames
	dw FroslassFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw StunfiskFrames
	dw HorseaFrames
	dw SeadraFrames
	dw KingdraFrames
	dw PawniardFrames
	dw BisharpFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw ScizorFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw ElectivireFrames
	dw MagmarFrames
	dw MagmortarFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw SylveonFrames
	dw GlaceonFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw ZangooseFrames
	dw LotadFrames
	dw LombreFrames
	dw LudicoloFrames
	dw HawluchaFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw SwirlixFrames
	dw SlurpuffFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PinsirFrames
	dw TynamoFrames
	dw EelektrikFrames
	dw EelektrossFrames
	dw AbsolFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw MurkrowFrames
	dw HonchkrowFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownFrames
	dw PinecoFrames
	dw ForretressFrames
	dw StuffulFrames
	dw BewearFrames
	dw GligarFrames
	dw GliscorFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw ShuckleFrames
	dw BergmiteFrames
	dw AvaluggFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw NoibatFrames
	dw NoivernFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw MakuhitaFrames
	dw HariyamaFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw SandileFrames
	dw KrokorokFrames
	dw KrookodileFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonzFrames
	dw SmeargleFrames
	dw CryogonalFrames
	dw GoomyFrames
	dw SliggooFrames
	dw GoodraFrames
	dw MiltankFrames
	dw BeldumFrames
	dw MetangFrames
	dw MetagrossFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw JirachiFrames
	dw DianceFrames
	assert_table_length NUM_POKEMON
