AnimationIdlePointers:
	table_width 2
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw PikipekAnimationIdle
	dw TrumbeakAnimationIdle
	dw ToucannonAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw CrobatAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	dw RoseliaAnimationIdle
	dw RoseradeAnimationIdle
	dw ShelmetAnimationIdle
	dw EscavalierAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw JoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw SableyeAnimationIdle
	dw FrillishAnimationIdle
	dw JellicentAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw MudbrayAnimationIdle
	dw MudsdaleAnimationIdle
	dw FomantisAnimationIdle
	dw LurantisAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw SkorupiAnimationIdle
	dw DrapionAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw FlabebeAnimationIdle
	dw FloetteAnimationIdle
	dw FlorgesAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw SlowkingAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw NuzleafAnimationIdle
	dw ShiftryAnimationIdle
	dw DrifloonAnimationIdle
	dw DrifblimAnimationIdle
	dw TyruntAnimationIdle
	dw TyrantrumAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw SteelixAnimationIdle
	dw StarlyAnimationIdle
	dw StaraviaAnimationIdle
	dw StaraptorAnimationIdle
	dw MawileAnimationIdle
	dw DarumakaAnimationIdle
	dw DarmanitanAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw SkrelpAnimationIdle
	dw DragalgeAnimationIdle
	dw LillipupAnimationIdle
	dw HerdierAnimationIdle
	dw StoutlandAnimationIdle
	dw FroslassAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw RhyperiorAnimationIdle
	dw ChanseyAnimationIdle
	dw BlisseyAnimationIdle
	dw TangelaAnimationIdle
	dw TangrowthAnimationIdle
	dw StunfiskAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw KingdraAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw ElectivireAnimationIdle
	dw MagmarAnimationIdle
	dw MagmortarAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw SylveonAnimationIdle
	dw GlaceonAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw GalladeAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw ZangooseAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw HawluchaAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw SwirlixAnimationIdle
	dw SlurpuffAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PinsirAnimationIdle
	dw TynamoAnimationIdle
	dw EelektrikAnimationIdle
	dw EelektrossAnimationIdle
	dw AbsolAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw MurkrowAnimationIdle
	dw HonchkrowAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw UnownAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw StuffulAnimationIdle
	dw BewearAnimationIdle
	dw GligarAnimationIdle
	dw GliscorAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw ShuckleAnimationIdle
	dw BergmiteAnimationIdle
	dw AvaluggAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw NoibatAnimationIdle
	dw NoivernAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw SandileAnimationIdle
	dw KrokorokAnimationIdle
	dw KrookodileAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonzAnimationIdle
	dw SmeargleAnimationIdle
	dw CryogonalAnimationIdle
	dw GoomyAnimationIdle
	dw SliggooAnimationIdle
	dw GoodraAnimationIdle
	dw MiltankAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw JirachiAnimationIdle
	dw DianceAnimationIdle
	assert_table_length NUM_POKEMON
